### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by benbattraw** [leeping/forcebalance#160]
When will the newest version of Force Balance be released? We are working with the genetic algorithm and were wondering if that would be updated in the next release. Line 1072 says that massive parallelization will be implemented and we were wanting if that would be implemented in the next release.

**Comment by leeping** [comment]
Hello Ben,

Thanks for your inquiry and I'm sorry for the long reply.  We're actively working on migrating the unit tests over to the pytest framework.  Once the tests are able to run on Travis, we will cut the 1.7.0 release.  Unfortunately, we haven't been working on the genetic algorithm lately and I should probably change the docs to make that clear.

- Lee-Ping
