### ISSUE TITLE
Python 2.7 Tests Failing

### ISSUE THREAD

**Issue by SimonBoothroyd** [leeping/forcebalance#174]
## Description

It seems like the Python 2.7 tests [are currently failing master](https://travis-ci.org/leeping/forcebalance/jobs/656665144?utm_medium=notification&utm_source=github_status) due to an
```
self = <forcebalance.output.RawStreamHandler object at 0x7f3b5cadd5d0>
record = <logging.LogRecord object at 0x7f3b409555d0>
    def emit(self, record):
        message = record.getMessage()
>       self.stream.write(message)
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 1931: ordinal not in range(128)
```
exception.

It looks like the 74cd43da66bb30933823ec21fecf379458b046e4 commit is the source of this error.

(cc @leeping)

**Comment by leeping** [comment]
Thanks @SimonBoothroyd! I think this issue should be fixed in the latest master. That taught me a lesson for pushing directly to master.
