### ISSUE TITLE
Not Compatable with Openforcefield toolkit 0.8.1

### ISSUE THREAD

**Issue by jthorton** [leeping/forcebalance#193]
In the recent openforcefield toolkit release 0.8.1 some extra arguments were added to some of the [functions](https://github.com/openforcefield/openforcefield/blob/4641ec15bce760e6e3ad0e15ead70dcf3191c361/openforcefield/utils/toolkits.py#L4378) which are currently replaced in this [file](https://github.com/leeping/forcebalance/blob/master/src/smirnoff_hack.py) to enable using a cache.  I think these functions now need to be updated to allow the passing of the extra arguments and it may be possible to future proof this issue using *args and **kwargs. 

Error message
`ToolkitWrapper around AmberTools version 20.0 <class 'TypeError'> : at_cached_assign_partial_charges() got an unexpected keyword argument '_cls'
`

 This error is shown when using forcebalance1.7.5, openforcefield0.8.1, ambertools 20.9

**Comment by j-wags** [comment]
Ah, I know what’s going on here. I'll open a PR for this ASAP, and in the meantime we can build a new conda package of forcebalance that pins to `openforcefield=0.8.0` until there's a new FB release.

**Comment by mattwthompson** [comment]
Just to update the current status; I'm pretty sure that #194 will fix this and it will require a release. It would be best to have CI back online by then, but that requires a migration from Travis to GitHub Actions (which I have mostly online here: https://github.com/mattwthompson/forcebalance/pull/1)
