### ISSUE TITLE
Version read fix for tinkerio.py

### ISSUE THREAD

**Issue by bdw2292** [leeping/forcebalance#204]
if "Version" in line:
                vw = line.split()[2]
                if len(vw.split('.')) <= 2:
                    vn = float(vw)
                else:
                    ls=vw.split('.')
                    last=ls[1:]
                    first=ls[0]
                    vn=first+'.'+''.join(last)
                    vn = float(vn)
Just change the way tinker version is read, this can handle 8.8.3 (rather than only 8.8) in tinkerio.py

**Comment by leeping** [comment]
Thanks, I've got it. :)

**Comment by leeping** [comment]
This will be in the next release, which will come out shortly.

**Comment by bdw2292** [comment]
Great thanks! On a side node, for work_queue_worker on your clusters, have
you had to mess with any firewall settings? Seem to be having trouble
getting master host to connect to workers, I can tell that my worker nodes
are listening on the port number I give.
