### ISSUE TITLE
AttributeError: 'ForceField' object has no attribute '_forces'

### ISSUE THREAD

**Issue by pavankum** [leeping/forcebalance#209]
[](url)
[forcebalance_error.tar.gz](https://github.com/leeping/forcebalance/files/6184067/forcebalance_error.tar.gz)

Hi Lee-ping, 

I am getting an attribute error while trying to do a fit with the new release. I attached a minimal example along with the conda-env I used. Please take a look when you have a moment. 

Thank you!

**Comment by leeping** [comment]
Hmm .. Could you change this line and let me know if it resolves the issue?

openmmio.py line 845
From this:
```
                elif any(['Drude' in f.__class__.__name__ for f in self.forcefield._forces]): integrator = DrudeLangevinIntegrator(temperature*kelvin, collision/picosecond, 1*kelvin, collision/picosecond, 0.1*femtoseconds)
```
To this:
```
                elif hasattr(self.forcefield, '_forces') and any(['Drude' in f.__class__.__name__ for f in self.forcefield._forces]): 
                    integrator = DrudeLangevinIntegrator(temperature*kelvin, collision/picosecond, 1*kelvin, collision/picosecond, 0.1*femtoseconds)
```

**Comment by leeping** [comment]
See https://github.com/leeping/forcebalance/pull/210
