### ISSUE TITLE
use_pvals option fails to work due to non-conversion to numpy array

### ISSUE THREAD

**Issue by pavankum** [leeping/forcebalance#220]
Hi Lee-ping,

In forcebalance/forcefield.py, at line 780, vals is a list when it is called from `opt_geo_target.py`, and flattening results in an attribute error:
`AttributeError: 'list' object has no attribute 'flatten'`
The following check can fix it
```
        if use_pvals or self.use_pvals: 
            logger.info("Using physical parameters directly!\r")
            if isinstance(vals, list):
                vals = np.array(vals)
            pvals = vals.copy().flatten()
```

Thank you!

**Comment by leeping** [comment]
Thank you, Pavan. Could you please make a PR with this fix?

- Lee-Ping
