### ISSUE TITLE
Large values with Hessian target

### ISSUE THREAD

**Issue by pavankum** [leeping/forcebalance#235]
Hi @leeping & @hyejang, I am trying out the internal coordinate hessian fitting and all my calculated hessian values are coming out large. I created an environment with `conda create -n fb_test --strict-channel-priority -c conda-forge -c openeye python=3.7 forcebalance openff-toolkit=0.9.1 geometric openeye-toolkits` and ran the example in `027_openff_hessian_target`, and here is the output:
[optimize.txt](https://github.com/leeping/forcebalance/files/7043936/optimize.txt). I couldn't figure out where it's going wrong, do you have any pointers on how to debug this?

**Comment by pavankum** [comment]
Found where the problem is, here https://github.com/leeping/forcebalance/blob/master/src/openmmio.py#L1183, the positions are wrong by one order of magnitude, but don't know why it is so. Going a bit deeper, the optimized geometry X1 is good, and up until this point (https://github.com/leeping/forcebalance/blob/master/src/smirnoffio.py#L537) the positions remain good, after setPositions() call there is change in the coordinate values by one order, that's confusing since it is happening in openmm.

**Comment by jthorton** [comment]
@pavankum I have just hit this issue as well during running a water simulation via the smirnoff interface where the molecular dipole is calculated to be 10x less than expected. I suspect that conversion between angstrom and nanometer is going wrong [here](https://github.com/leeping/forcebalance/blob/a3fe9bd11a51e216049f15467ecb35c67a661a53/src/smirnoffio.py#L537) I think the positions are being wrapped in angstrom twice which causes openmm to do an incorrect conversion to nanometer when setting the positions. Can you try and remove the last `* angstrom` this worked for me.

**Comment by pavankum** [comment]
Awesome @jthorton!! Yeap, that works, thanks for putting in the fix :)
