### ISSUE TITLE
Compatibility with OpenMM-7.7.0

### ISSUE THREAD

**Issue by jthorton** [leeping/forcebalance#246]
OpenMM 7.7 introduced a lot of argument checks in functions which are causing some tests to fail which involve liquid simulations see [here](https://github.com/leeping/forcebalance/runs/4970177002?check_suite_focus=true#step:12:393) for an example.

**Comment by leeping** [comment]
Thanks, Josh. Is there any argument we could pass to OpenMM so that it disables these argument checks?  The extra arguments are harmless, but on our end it would take a lot of effort to make sure our code doesn't pass an extra argument that would cause OpenMM to throw an error.

**Comment by jthorton** [comment]
Unfortunately, I don't think so this seems to be hardcoded in now. It might be worth asking for an option to stop the checks.

**Comment by leeping** [comment]
After looking at your link more carefully, I saw that the error was thrown when the keyword arg `useSwitchingFunction` was set, but it seems to no longer be part of the OpenMM API; it may have been in the past.  Maybe removing that from the FB source code is a better solution.  I'm currently working on something and will hopefully get to this soon, but I'd also be happy to review a PR if you want to do it.

**Comment by leeping** [comment]
(I also understand that this is just an example, and there may be other errors that could not be fixed so easily...)
