### ISSUE TITLE
use openff-units for conversion factors (not urgent)

### ISSUE THREAD

**Issue by pavankum** [leeping/forcebalance#265]
Since we have a [light weight units package](https://github.com/openforcefield/openff-units) now it might be beneficial if we eliminate hardcoded conversion factors or constants in some future release.

**Comment by leeping** [comment]
Hi Pavan,

Thanks for the feedback.  Although I do see the benefit of having standardized physical constants, I think that is outweighed by the benefit of not introducing additional dependencies unless absolutely necessary.  If an external unit package changes in an API-breaking way, or if it becomes deprecated itself, I'm concerned that would break this code in a way that requires checking every line that involves a unit conversion (which would be in the hundreds).  I've already had this happen twice, once with Python 3 changing the division operator, and again with NumPy deprecating its matrix class.  Both times it was a difficult process that had the potential to introduce bugs, and the experiences have made me question whether Python was the correct language to develop long-term projects in.

Additionally, even though this PR is for ForceBalance, I could see the same argument applying to geomeTRIC.  GeomeTRIC is currently very lightweight in its dependencies and I think it's important to keep it that way.

- Lee-Ping

**Comment by pavankum** [comment]
Thank you for the clarification Lee-Ping.
