### ISSUE TITLE
Replicating Results

### ISSUE THREAD

**Issue by alexW432** [leeping/forcebalance#82]
Hello,
I want to use particular targets in an optimization. To check the liquid.pdb, gas.pdb and file.in are correct I tried to use them to replicate the results this paper obtained for tip4p-fb http://dx.doi.org/10.1021/jz500737m However whilst the density and heat of vaporisation are close the static dielectric constant is around 5 instead of 77. Is there something else I should add to my targets to replicate this result? 
This is my liquid.pdb:
```Python
CRYST1   20.000   20.000   20.000  90.00  90.00  90.00 P 1           1
ATOM      1  O   HOH    1       9.457  18.861  18.736  1.00  0.00      QQQ   
ATOM      2  H1  HOH    1       8.845  19.288  19.335  1.00  0.00      QQQ   
ATOM      3  H2  HOH    1      10.058  19.557  18.471  1.00  0.00      QQQ   
ATOM      4  M   HOH    1       9.456  19.004  18.779  1.00  0.00      QQQ   
.........
```
however with 233 molecules, I could email the rest. 
This is the gas.pdb:
```Python
CRYST1   20.000   20.000   20.000  90.00  90.00  90.00 P 1           1
ATOM      1  O   HOH    1       1.457   0.861   0.736  1.00  0.00      QQQ   
ATOM      2  H1  HOH    1       0.845   1.288   1.335  1.00  0.00      QQQ   
ATOM      3  H2  HOH    1       2.058   1.557   0.471  1.00  0.00      QQQ   
ATOM      4  M   HOH    1       1.456   1.004   0.779  1.00  0.00      QQQ 
```
the data.csv: 
T,P,MBAR,Rho,Rho_wt,Hvap,Hvap_wt,Eps0,Eps0_wt
298.15,1.0 atm,TRUE,997.045,1.0,43.989,1.0,78.409,1.0
the file.in:
```Python
$options
forcefield tip4pfb.xml
jobtype newton
$end
$target
type Liquid_OpenMM
name WATER
# Parameters for self-polarization correction of nonpolarizable water
self_pol_mu0 1.855
self_pol_alpha 1.470
$end
```
where tip4pfb.xml is the force field provided in simtk/openmm/app/data in openMM. Thank you in advance.
Alex

**Comment by leeping** [comment]
Hi Alex,

I think you mainly need to increase `liquid_eq_steps` and `liquid_md_steps`.  Try these values:

```
liquid_eq_steps 50000
liquid_md_steps 500000
gas_eq_steps 50000
gas_md_steps 500000
# liquid_timestep 2.0
# liquid_interval 0.2
```

To use a 2.0 fs time step, make sure your water molecules are rigid with `rigid_water true` in `$options`.

Thanks,

- Lee-Ping

**Comment by alexW432** [comment]
Thank you, I will try this now.
Alex

**Comment by alexW432** [comment]
It is much better now thank you :). Could I ask, how does Force Balance determine the cutoff for a periodic system, does it read the box size and half it? And is there a way to use the position and height of a RDF as a target?
Many Thanks,
Alex

**Comment by leeping** [comment]
Hi Alex,

You can set this value yourself by setting `nonbonded_cutoff` in `$target` (in Angstrom), and ForceBalance uses the default value of 8.5 Angstrom.  


I basically chose this number because it was safely less than half the size of a 216-water box.  An isotropic vdW correction is applied which affects the density but not the forces directly.

https://github.com/leeping/forcebalance/blob/master/src/openmmio.py#L675

There is no feature right now for targeting the RDF, but this is something I'm interested in implementing.  Let me know if you might like to potentially work on this together.

Thanks,

- Lee-Ping
