### ISSUE TITLE
How are the gradients determined?

### ISSUE THREAD

**Issue by mohebifar** [leeping/forcebalance#95]
Okay, this is more of a question than a bug report. And I'm sorry for asking it here, I couldn't find the answer by reading the code/docs.

I am using the study `#7` (007_tip4p_STP) with a few modifications.
1. I have deleted the `AbInitio` target.
2. Using OpenMM instead of Gromacs

Using that, I've tried reparametrizing the charge for a simple water model and everything seems to be working perfectly and optimization is done after a couple of iterations.

I noticed that a `mvals` is written at every iteration which contains the gradients, and that is used as a direction for the next iterations.

Now, I have modified the OpenMM's NonBonded code, introducing some new parameters (c6, c8, c10, c12). ForceBalance still does a perfect job reparameterizing the charges with the modified OpenMM code and the gradients are not zero. But when I try to reparametrize the new parameter, it stops after the first iteration and I realized the reason is that the gradient is `0.0` in the mvals file. So my question is how are the gradients determined? Why do I get zero gradients?

[Here's my forcefield file](https://gist.github.com/mohebifar/2e4fdef37107ecea5996501db1f237cf#file-water-xml-L31)

**Comment by leeping** [comment]
Hi there,

The gradients of thermodynamic properties are determined in `npt.py`.  After the simulation is finished, ForceBalance writes out a parameter file with perturbed parameters (i.e. one of the mvals is changed by finite_difference_h) and recalculates the potential for every simulation snapshot, thus getting the energy derivative by finite difference (i.e. dE/dp = [E(p+h)-E(p)]/h.  dE/dp is then contracted with the property to get the derivative, like this: d(rho)/dp = -Beta*[<dE/dp rho> - <dE/dp> <rho>].

The main point here is that ForceBalance is mostly agnostic to the physical meaning of the parameter.  If changing the parameter affects the potential energy, then ForceBalance should be able to calculate a property derivative from that.  I would start troubleshooting by testing whether changing the c6, c8, c10, c12 parameters in the force field file actually affects the energies of your water box.  It's possible these parameters are not being used in the simulation for example.

Thanks,

- Lee-Ping

**Comment by mohebifar** [comment]
Thank you very much for your prompt response and the great explanation.

I tried printing out the energy derivatives in npt.py and I obviously got `0.0`, however, by printing out the positions from the State, I noticed this all belongs to the gas phase which in my case, it totally makes sense for C12 not to make any effect on the potential energy of the system. C12 is basically for the repulsive term in LJ (C12/r12) and since Hydrogen's C12 is set to 0 and there is only one Oxygen in the gas system, it wouldn't have any effect on the energy. Is there a way to tell ForceBalance to use the liquid phase for energy derivatives?

**Comment by leeping** [comment]
npt.py should be running a liquid phase simulation and a gas phase simulation.  It will calculate energy derivatives for both simulations, and I think the derivatives should be nonzero for the former.  The gas phase energy derivatives are only for the heat of vaporization.

Thanks,

- Lee-Ping

**Comment by mohebifar** [comment]
True. I was getting energies for condensed matter too and it was being printed out before the gas one and that's why I missed it. And it makes sense that both derivatives are needed.

Now I think I figured out what the issue was. My initial XML file was formatted like this:
```xml
  <Atom
    type="OW"
    charge="-8.531254509373e-01"
    sigma="0.317796456355"
    epsilon="0.652143528104"
    c6="0.0026399910"
    c8="0.0001937841"
    c10="0.0"
    c12="4.696188795608e-06"
    parameterize="c12,charge"
  />
```

And after the first change by ForceBalance, it looked like this:

```xml
<Atom type="OW" charge="-8.531254509373e-01" sigma="0.317796456355" epsilon="0.652143528104" c6="0.0026399910" c8="0.0001937841" c10="0.0" c12="4.696188795608e-06" parameterize="c12,charge" />
```

After rewriting the XML file by etree, the formatting had changed so that the `c12` parameter was moved to another line. Since FF uses the line number for manipulating the XML attributes, now it wasn't able to tweak the parameters as it had lost the correct line number.

([forcefield.py#L781](https://github.com/leeping/forcebalance/blob/master/src/forcefield.py#L781))

**Comment by leeping** [comment]
Thanks; I think I see what’s going on.  I think this issue should be fixed because you wrote a valid XML file (as far as I know), and the ForceBalance XML parser / reader shouldn’t break down if you provide files that are still in the XML standard.

At forcefield.py L639, a list of lines is created corresponding to the force field XML file that is read in.  This is used in “reading” the force field and assigning a line number to each parameter.  If the line numbers are different when the force field is written back out (forcefield.py L744), that may cause an issue.

I think one easy workaround would be to take your initial XML file, have etree write a copy of it to disk, and then read in the copy as the input force field XML file.  If we assume that etree writes out files in some fixed way (e.g. where all attributes are on a line), then the line numbers in the “preprocessed file” shouldn’t be any different when it’s time to write the force field out.  What do you think?

We should also throw some kind of error message when a parameter fails to be written, instead of producing the undefined behavior that you got.  Can you suggest any way to check for this?

Let me know if you’re willing to try these suggested fixes, or if I should do that.

- Lee-Ping

**Comment by mohebifar** [comment]
Thank you very much for your response.

My assumption about the issue with writing the XML file was invalid. The variable name was a bit misleading, it's actually the position of the XML element in the Tree not the "line number" which should be consistent for any XML formatting.

Finally, I figured it out. I had not implemented the `copyParametersToContext` method properly in my OpenMM code, hence it wasn't able to update the parameters. I'm still surprised that initializing parameters happens in a separate routine versus updating them (duplicate code).

**Comment by adw62** [comment]
Apologies for opening an old issue, I'm also interested in calculating gradients w.r.t force field parameters for thermodynamic integration.

Please may I ask. Does ForceBalance still calculate the gradient as described here?

Would the getEnergyParameterDerivatives function in OpenMM work for this purpose or are there disadvantages to this?

I would be interested in any input on this.

Thanks,
Alex
