### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by tobigithub** [leeping/forcebalance#97]
I wonder if there is any fork that already has python 3.6 support for forcebalance,
Like  here: https://www.digitalocean.com/community/tutorials/how-to-port-python-2-code-to-python-3
Or maybe its not worthwhile and rather use conda and python 2.7?
Tobias

**Comment by leeping** [comment]
Hi Tobias,

I’m interested in having Python 3 support for ForceBalance, but making everything compatible with the same results is going to take some effort. 

I expect that within a year everything will be done. There is some potential funding for a software scientist to help with the port.

Thanks,

- Lee-Ping

**Comment by tobigithub** [comment]
Tnx
